/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashBoard;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author SAMIR
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        
        Lista_medicos p1 = new Lista_medicos();
        p1.setSize(600, 370);
        p1.setLocation(0, 0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        panelMed = new javax.swing.JPanel();
        btnMedicos = new javax.swing.JLabel();
        panelPac = new javax.swing.JPanel();
        btnPacientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 370));

        panelMed.setBackground(new java.awt.Color(0, 102, 255));
        panelMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMedMouseExited(evt);
            }
        });

        btnMedicos.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnMedicos.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMedicos.setText("MÉDICOS");
        btnMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMedicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMedicosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMedLayout = new javax.swing.GroupLayout(panelMed);
        panelMed.setLayout(panelMedLayout);
        panelMedLayout.setHorizontalGroup(
            panelMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        panelMedLayout.setVerticalGroup(
            panelMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 298, 70));

        panelPac.setBackground(new java.awt.Color(0, 102, 255));
        panelPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPacMouseExited(evt);
            }
        });

        btnPacientes.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPacientes.setText("PACIENTES");
        btnPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPacientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPacLayout = new javax.swing.GroupLayout(panelPac);
        panelPac.setLayout(panelPacLayout);
        panelPacLayout.setHorizontalGroup(
            panelPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        panelPacLayout.setVerticalGroup(
            panelPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacLayout.createSequentialGroup()
                .addComponent(btnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(panelPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 298, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMedMouseEntered
        panelMed.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_panelMedMouseEntered

    private void panelMedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMedMouseExited
        panelMed.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_panelMedMouseExited

    private void panelPacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPacMouseEntered
        panelPac.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_panelPacMouseEntered

    private void panelPacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPacMouseExited
        panelPac.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_panelPacMouseExited

    private void btnMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicosMouseClicked
        Lista_medicos p1 = new Lista_medicos();
        ShowPanel(p1);
    }//GEN-LAST:event_btnMedicosMouseClicked

    private void btnPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacientesMouseClicked
        Lista_pacientes p2 = new Lista_pacientes();
        ShowPanel(p2);
    }//GEN-LAST:event_btnPacientesMouseClicked

    private void btnMedicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicosMouseEntered
        panelMed.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_btnMedicosMouseEntered

    private void btnMedicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicosMouseExited
        panelMed.setBackground(new Color(0, 102, 255));

    }//GEN-LAST:event_btnMedicosMouseExited

    
    private void ShowPanel(JPanel p){
        p.setSize(600, 370);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnMedicos;
    private javax.swing.JLabel btnPacientes;
    private javax.swing.JPanel content;
    private javax.swing.JPanel panelMed;
    private javax.swing.JPanel panelPac;
    // End of variables declaration//GEN-END:variables
}
